### ISSUE TITLE
Entering an August roast date appears to be impossible

### ISSUE THREAD

**Issue by denschub** [ebengoechea/de1app_plugin_DYE#5]
I'm running DYE on a nightly v1.40.1.20 de1app. My "Roast date format" is set to `%Y-%m-%d`.

This setup worked fine for me, but today, I discovered I can't actually enter an August roast date. When I leave the field after typing, for example, `2022-08-14`, the date jumps to `2022-09-14`. All possible August dates appear to behave this way, they all jump to September. `2022-07-14`, however, works fine.

For reference, here's a screen recording showing that behavior:

https://user-images.githubusercontent.com/344777/192159219-827e2312-f10e-4f5b-ae41-6e145cfc18df.mp4

**Comment by ebengoechea** [comment]
Fixed on v2.26
